title: My Devlog
baseurl: "/devlog"   # important for GitHub Pages
url: "https://username.github.io"
encoding: utf-8

markdown: kramdown
theme: minima

permalink: /:title/   # ensures /post-name/index.html
